### PR TITLE
html output

### PR DESCRIPTION
**Pull request by tomaskovacik**
hello,

if you like, html output of colorize.pl i create it a year ago, using it since with no problem.

### CODE REVIEW

**Comment by 4ndrej** [comment]
nice, thanks!

I see one possible improvement here - if there is just one background color selected it could be set as global background color. The common terminal background color is black and using it on default while html background looks strange.

**Comment by tomaskovacik** [comment]
hi, i don't get it :) which one bg color?

**Comment by 4ndrej** [comment]
if there is just one bg colour specified (mainly it's black) the page's bg colour should be that colour too.

**Comment by tomaskovacik** [comment]
hmm, I try -n47:something -n4:something2 and it gime me error that -n4: is not correct

**Comment by 4ndrej** [comment]
let's have -n47:something -n57:something2
it will detect that 7 is common bg colour and it will set colour7 as bg colour of whole page.

**Comment by tomaskovacik** [comment]
oo i got it know, hmm check for bg colour prior to call html header function and set bg for body element, ok, i take a look on it when I have time

t

**Pull request merged**
